"use client";
import React, { useEffect, useState } from "react";
import axios from "axios";
import { useRouter } from "next/navigation";
import Head from "next/head";
import { signIn, useSession } from "next-auth/react";
import Link from "next/link";
import SignUp from "./SignUp";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
const Login = () => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [loginData, setLoginData] = useState();
  const router = useRouter();

  const handleLogin = async (e) => {
    e.preventDefault();
    const payload = { username: email, password: password };

    try {
      const response = await axios.post(
        `${process.env.NEXT_PUBLIC_AUTH_URL}/user/login`,
        payload
      );
      setLoginData(response);
      console.log("response -----", response.data);
      if (response.data.message == "success") {
        toast("Login Successfully");
      } else {
        toast("Something went wrong...");
      }
    } catch (error) {
      toast("Login UnSuccessfully");

      console.error(error, "gggggggggggggggggg");
    }
  };

  useEffect(() => {
    const accessToken = localStorage.getItem("accessToken");
    // if (!accessToken) router.push('/Login')
    if (accessToken) router.push("/");
  }, []);

  useEffect(() => {
    console.log("loginData:::::::::", loginData?.data?.data);
    if (loginData?.data?.data) {
      localStorage.setItem("accessToken", loginData?.data?.data);
      localStorage.setItem("user", JSON.stringify(loginData?.data?.data));
      router.push("/");
    }
  }, [loginData]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous"
        ></link>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
          crossorigin="anonymous"
        ></script>
        <link
          href="https://use.fontawesome.com/releases/v5.0.4/css/all.css"
          rel="stylesheet"
        />
      </Head>
      <div className="login-bg">
        <div className="container-fluid">
          <div className="row">
            <div className="col-sm-6 p0">
              <div className="col-login-left">
                <div className="col-login-logo">
                  <a href="">
                    <img src="images/logo2.png" />
                  </a>
                </div>
                <div className="col-login-banner">
                  <img src="images/login-bg.png" />
                </div>
              </div>
            </div>

            <div className="col-sm-6 p0">
              <div className="col-login-right">
                <nav>
                  <div className="nav nav-tabs" id="nav-tab" role="tablist">
                    <button
                      className="nav-link active"
                      id="nav-home-tab"
                      data-bs-toggle="tab"
                      data-bs-target="#login"
                      type="button"
                      role="tab"
                      aria-controls="nav-home"
                      aria-selected="true"
                    >
                      Log in
                    </button>
                    <button
                      className="nav-link"
                      id="nav-profile-tab"
                      data-bs-toggle="tab"
                      data-bs-target="#joinin"
                      type="button"
                      role="tab"
                      aria-controls="nav-profile"
                      aria-selected="false"
                    >
                      Join Now!
                    </button>
                  </div>
                </nav>
                <div className="tab-content" id="nav-tabContent">
                  <div
                    className="tab-pane fade show active"
                    id="login"
                    role="tabpanel"
                    aria-labelledby="nav-home-tab"
                  >
                    <div className="login-box">
                      <div className="login-box-input">
                        <label>Email/Username</label>
                        <div className="login-box-input_box">
                          <span>
                            <img src="images/email.png" />
                          </span>
                          <input
                            type="email"
                            name="email"
                            value={email}
                            onChange={(e) => setEmail(e.target.value)}
                            required
                          />
                        </div>
                      </div>
                      <div className="login-box-input">
                        <label>Password</label>
                        <div className="login-box-input_box">
                          <span>
                            <img src="images/password.png" />
                          </span>
                          <input
                            type="password"
                            name="password"
                            value={password}
                            onChange={(e) => setPassword(e.target.value)}
                            required
                          />
                        </div>
                      </div>
                      <div className="login-box-input">
                        <label>Forgot your password?</label>
                      </div>
                      <div className="login-box-submit">
                        <button onClick={handleLogin}>Log in</button>
                        <small>OR</small>
                        <span>
                          <img src="images/border.png" />{" "}
                        </span>

                        <p>
                          By continuing, you agree to our
                          <a href="">Terms of use</a>,
                          <a href="">Terms of Service</a>, and
                          <a href="">Privacy Policy</a>.
                        </p>
                      </div>
                      <div className="login-social-button">
                        <div
                          className="social-button social-button-fb"
                          onClick={() => signIn("facebook")}
                        >
                          <Link href={""}>
                            <span>
                              <img src="images/fb.png" />
                            </span>{" "}
                            Connect with Facebook
                          </Link>
                        </div>
                        <div
                          className="social-button social-button-google"
                          onClick={() => signIn("google")}
                        >
                          <Link href={""}>
                            <span>
                              <img src="images/google.png" />
                            </span>
                            Connect with Google
                          </Link>
                        </div>
                        <div className="social-button social-button-apple">
                          <Link href={""}>
                            <span>
                              <img src="images/apple.png" />{" "}
                            </span>
                            Connect with Apple
                          </Link>
                        </div>
                      </div>
                    </div>
                  </div>

                  <SignUp />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Login;
